version: "3"
services:
  cloudeyes-ai:
    container_name: cloudeyes-ai
    env_file: ./env/.env
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/code/app
    links:
      - cloudeyes-ai-mongo

  cloudeyes-ai-mongo:
    container_name: cloudeyes-ai-mongo
    image: mongo
    volumes:
      - ~/cloudeyes_ai_mongo:/data/db
    ports:
      - '27018:27017'